name: Deployment application

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Configuration de la clé SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ajouter HOST aux hôtes connus (Known Hosts)
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies & Build
      run: |
        npm ci
        npx ng build --configuration fr

    - name: Create .htaccess
      run: |
        echo "<IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
        </IfModule>" > dist/fr/browser/.htaccess

    - name: Synchronization Files
      env:
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_USER: ${{ secrets.SSH_USER }}
        FTP_SERVER_DIR: ${{ secrets.FTP_SERVER_DIR }}
        DOMAIN_URL: ${{ secrets.DOMAIN_URL }}
      run: |
        rsync -avz --checksum --no-perms --no-owner --no-group --delete \
          --exclude='.git*' \
          --exclude='.htaccess' \
          --exclude='config.json' \
          ./ $SSH_USER@$SSH_SERVER:$FTP_SERVER_DIR/